version: '2'
services:
  scraper:
    container_name: scraper
    build: .
    volumes:
      - .:/opt/scraper
    working_dir: /opt/scraper
    command: bash -c "node scrap hackernews --posts 100"
    ports:
      - "3000:3000"
      - "5858:5858"
      - "35729:35729"
